//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed_Market.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursed_Market.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOODWEB LEVEL.
        /// </summary>
        internal static string CHARACTERSPRESET_BloodWebTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_BloodWebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CHARACTER.
        /// </summary>
        internal static string CHARACTERSPRESET_CharacterSelectTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_CharacterSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIGURE CHARACTERS PRESET.
        /// </summary>
        internal static string CHARACTERSPRESET_CharactersPresetTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_CharactersPresetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTRA ACTIONS.
        /// </summary>
        internal static string CHARACTERSPRESET_ExtraActionsTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_ExtraActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEGACY PRESTIGE LEVEL.
        /// </summary>
        internal static string CHARACTERSPRESET_LegacyPrestigeTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_LegacyPrestigeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESTIGE LEVEL.
        /// </summary>
        internal static string CHARACTERSPRESET_PrestigeTitle {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_PrestigeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize all characters presets.
        /// </summary>
        internal static string CHARACTERSPRESET_RandomizePresets {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_RandomizePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and Save Changes.
        /// </summary>
        internal static string CHARACTERSPRESET_SaveChanges {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spread current preset among all characters.
        /// </summary>
        internal static string CHARACTERSPRESET_SpreadPreset {
            get {
                return ResourceManager.GetString("CHARACTERSPRESET_SpreadPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud-ID to Send a Friend Request to.
        /// </summary>
        internal static string FRIEND_FriendCloudIDTitle {
            get {
                return ResourceManager.GetString("FRIEND_FriendCloudIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cloud-ID.
        /// </summary>
        internal static string FRIEND_MyCloudIDTitle {
            get {
                return ResourceManager.GetString("FRIEND_MyCloudIDTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOUD-ID FRIEND REQUEST.
        /// </summary>
        internal static string FRIEND_Title {
            get {
                return ResourceManager.GetString("FRIEND_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s rock! 🤘.
        /// </summary>
        internal static string GREETINGS_01 {
            get {
                return ResourceManager.GetString("GREETINGS_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How&apos;s your day been?.
        /// </summary>
        internal static string GREETINGS_02 {
            get {
                return ResourceManager.GetString("GREETINGS_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s groove! 🕺.
        /// </summary>
        internal static string GREETINGS_03 {
            get {
                return ResourceManager.GetString("GREETINGS_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming Time! ⚔.
        /// </summary>
        internal static string GREETINGS_04 {
            get {
                return ResourceManager.GetString("GREETINGS_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to groove! 🎵.
        /// </summary>
        internal static string GREETINGS_05 {
            get {
                return ResourceManager.GetString("GREETINGS_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another day, another challenge!.
        /// </summary>
        internal static string GREETINGS_06 {
            get {
                return ResourceManager.GetString("GREETINGS_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s roll! 🎲.
        /// </summary>
        internal static string GREETINGS_07 {
            get {
                return ResourceManager.GetString("GREETINGS_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to shine! ✨.
        /// </summary>
        internal static string GREETINGS_08 {
            get {
                return ResourceManager.GetString("GREETINGS_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From time to time, some ingame items may appear to be bugged, so developers turn them off. This restriction has now been removed..
        /// </summary>
        internal static string MAIN_AntiKillSwitchDescription {
            get {
                return ResourceManager.GetString("MAIN_AntiKillSwitchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KillSwitch Remover Status:  .
        /// </summary>
        internal static string MAIN_AntiKillSwitchTitle {
            get {
                return ResourceManager.GetString("MAIN_AntiKillSwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bhvrSession will be shown here....
        /// </summary>
        internal static string MAIN_BhvrSession {
            get {
                return ResourceManager.GetString("MAIN_BhvrSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROSSHAIR OPACITY.
        /// </summary>
        internal static string MAIN_CrosshairOpacityTitle {
            get {
                return ResourceManager.GetString("MAIN_CrosshairOpacityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROSSHAIR.
        /// </summary>
        internal static string MAIN_CrosshairTitle {
            get {
                return ResourceManager.GetString("MAIN_CrosshairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCIES AMOUNTS.
        /// </summary>
        internal static string MAIN_CurrenciesAdjustTitle {
            get {
                return ResourceManager.GetString("MAIN_CurrenciesAdjustTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some customization sets were designed so they only show up and release at the very specific date. This restriction has now been removed..
        /// </summary>
        internal static string MAIN_CustomizationsKingDescription {
            get {
                return ResourceManager.GetString("MAIN_CustomizationsKingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizations King Status:  .
        /// </summary>
        internal static string MAIN_CustomizationsKingTitle {
            get {
                return ResourceManager.GetString("MAIN_CustomizationsKingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently In Use.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_CurrentlyInUse {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_CurrentlyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_Disabled {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed To Obtain.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_FailedToObtain {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_FailedToObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE MODE.
        /// </summary>
        internal static string MAIN_GAMECHANGERSTATUS_Offline {
            get {
                return ResourceManager.GetString("MAIN_GAMECHANGERSTATUS_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME CHANGERS.
        /// </summary>
        internal static string MAIN_GameChangersTitle {
            get {
                return ResourceManager.GetString("MAIN_GameChangersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Position Overlay.
        /// </summary>
        internal static string MAIN_MainCheckBox_01 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust Currencies Amount (Visual).
        /// </summary>
        internal static string MAIN_MainCheckBox_02 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Temporary SaveFile.
        /// </summary>
        internal static string MAIN_MainCheckBox_03 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Characters Preset.
        /// </summary>
        internal static string MAIN_MainCheckBox_04 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Game Changers.
        /// </summary>
        internal static string MAIN_MainCheckBox_05 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Unlock DLC&apos;s.
        /// </summary>
        internal static string MAIN_MainCheckBox_06 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guaranteed Quest Completion.
        /// </summary>
        internal static string MAIN_MainCheckBox_07 {
            get {
                return ResourceManager.GetString("MAIN_MainCheckBox_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN FEATURES.
        /// </summary>
        internal static string MAIN_MainFeaturesTitle {
            get {
                return ResourceManager.GetString("MAIN_MainFeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MAIN_NOTIFYICON_Close {
            get {
                return ResourceManager.GetString("MAIN_NOTIFYICON_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string MAIN_NOTIFYICON_Show {
            get {
                return ResourceManager.GetString("MAIN_NOTIFYICON_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOBBY FOUND....
        /// </summary>
        internal static string MAIN_QUEUE_LobbyFound {
            get {
                return ResourceManager.GetString("MAIN_QUEUE_LobbyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCH STARTING!.
        /// </summary>
        internal static string MAIN_QUEUE_MatchStarting {
            get {
                return ResourceManager.GetString("MAIN_QUEUE_MatchStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUEUE POSITION:.
        /// </summary>
        internal static string MAIN_QUEUE_QueuePosition {
            get {
                return ResourceManager.GetString("MAIN_QUEUE_QueuePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string MAIN_Start {
            get {
                return ResourceManager.GetString("MAIN_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes were made to the character preset, but they were not saved. Do you want to close the window without saving?.
        /// </summary>
        internal static string MESSAGE_CharactersPresetUnsavedChanges {
            get {
                return ResourceManager.GetString("MESSAGE_CharactersPresetUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursed Market failed to create data folder in %localappdata%! Please, verify that program is running with administrator privileges..
        /// </summary>
        internal static string MESSAGE_DataFolderCreationFailed {
            get {
                return ResourceManager.GetString("MESSAGE_DataFolderCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read &quot;charactersPreset.json&quot; file! Make sure that file isn&apos;t empty and it&apos;s content is in JSON format..
        /// </summary>
        internal static string MESSAGE_FailedToReadCharactersPreset {
            get {
                return ResourceManager.GetString("MESSAGE_FailedToReadCharactersPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Cursed Market!
        ///
        ///This software is Open-Source and Free To Use! In case you&apos;ve been convinced into paying for it, it&apos;s recommended to send seller a complaint..
        /// </summary>
        internal static string MESSAGE_FirstLaunch {
            get {
                return ResourceManager.GetString("MESSAGE_FirstLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursed Market was designed with &quot;Roboto-Regular&quot; font in mind!
        ///
        ///Software won&apos;t work properly until the font is installed: &quot;{0}&quot;.
        /// </summary>
        internal static string MESSAGE_RobotoFontMissing {
            get {
                return ResourceManager.GetString("MESSAGE_RobotoFontMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUEUE POSITION WILL BE SHOWN HERE.
        /// </summary>
        internal static string QUEUE_Idle {
            get {
                return ResourceManager.GetString("QUEUE_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~ LOBBY FOUND ~.
        /// </summary>
        internal static string QUEUE_LobbyFound {
            get {
                return ResourceManager.GetString("QUEUE_LobbyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCH STARTING!.
        /// </summary>
        internal static string QUEUE_MatchStarting {
            get {
                return ResourceManager.GetString("QUEUE_MatchStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, wait....
        /// </summary>
        internal static string STARTUP {
            get {
                return ResourceManager.GetString("STARTUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Although this program unlocks access to all in-game characters, attempts to use characters you don&apos;t actually own will result in being kicked back to the main menu, followed by a temporary ban!.
        /// </summary>
        internal static string WARNING_CharacterOwnership {
            get {
                return ResourceManager.GetString("WARNING_CharacterOwnership", resourceCulture);
            }
        }
    }
}
