//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed_Market.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OfflineAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OfflineAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursed_Market.Properties.OfflineAPI", typeof(OfflineAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BloodWebData {
            get {
                return ResourceManager.GetString("BloodWebData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJytvVl3GknyPvxdfN0XsmS3230n0GZt0IDk454zRyehEqhWUcXUYoz/Z777+0Rm7cgRv2DeC/YnqKyM3CPiif/3Lgqz/N2f//p/7xZrk5pFbtNHs7Hv/nx3sQtX6/zdb+8iuzKL/Ti1WR6u7L39bqN3f5781gh8ye0mc/8R4t2XAML01cvQbLY2fTmP7I9sliTRPPmBv/tPYeI8zPfv/vx48t/ffiEzsLjUg9n+n/Fp8mrjO7v/vwoMk80mCcKk0JbsoogixXUu41UYW5sqr3IVpnaB2n2loq7xD5n9P4tGJltHpe6UEienR8ic/V9lFNX2YNG64nCh1c6DDe7C//ONe/T//aZL/P/5hkv8h/8rfmLCeJ7sFO1eWT1fkzROivz/KjUlJbveaNI8/T+UqhIYrnEnmdn9nwXG0HaebGb/l4sctsD/cwVDIa9QyMf/K/6+iM3/0nXP4zj8btPMpPvTk/ef/8/VcW2yQbKZ/5/xd6fvx8nOpvq66xbx9ERX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterData {
            get {
                return ResourceManager.GetString("CharacterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJwlkc1u2zAQhN/F5xwckW6ao38SF95GacBD0RY50DItEaYogxJj9O3NGR08WpCc/WbX/xa7m2+7afGweHNt0W2w+eSmyZX6YC/41M4WXTeot11uLsGNpdwMx6I/fAib8vtf6t9+ajo8HaFSVUVNpWGzMfqjDTxWPF4V/Wlz8mhrOnvF99VFhJDS0KXlEyjOJjzoB2YRtjPVNyoe1Ijf24Tbj+zi5GOpfnn0eUm+oQmwbRhuuBLL4czVJ4+51yfbs9t3Pp07PyOda/0Ax8Gdz7wDz6glYpWEwATb5nlVcY6HJkY9Ft13wzidLdcmbGgUN6KwgJ3rh3ZILQG1jQ0WaCb3hefv0Rf9k6F1TiPO9jmOwcfWYR1/bfIR/4pUSGO4aqmANfN+FfekMLhRnEnN6eeAjKPp1XRpRtP0ano1vZpeTa+mV9O7gle4C+G4wuGEwwnpQrqQLqQL6UK6kC6kC+lCupAupAvpQrqQLqRLoX/eATElrDw=.
        /// </summary>
        internal static string CharactersList {
            get {
                return ResourceManager.GetString("CharactersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJyNfd132zgO7/8yz/vQpJ3dmfsWO19t7MYTu8mZvWePD23Rtjay6NVHU/ee+7/vDyApghKV2QfbAkBJIEiCAAjS/++Xk65e61/+z//95eHjPxYfLn75m7249BcfcTE1VdWems9lo6vvumxyUwL7udzpLa7b+rbK94cGqGtVvV7r78aVmBTGZC+qyjRBt3mlv51w8aSP+rjR1VwDWH76aF/LF/RavqDXPn7X1dtBF8e83C8qXetyS3fMTZk3proqs6tNWxPmTpe6UsDRHduDqvb2yZ/8k3Fhn4wLevJ1Xm9NlSn3QJXdVTnx/7ky5VHllt+l+q7Xq4NeT3TdrG9NtZ6pmmt5BkPrmavzolDn9UveHNZ/mrZCOZPxqy79y3FhX44Levm9KvdHVdarKt++EqGFUPOi6Lh51fSk6cHkjPh8vCqKG1XVuF4dKpTE61eVPhpG3bZVk3/X04NiWeBpXPt5XmabSuNhFbVg1epiaspdXkL4JfE9mfwBEU4P9Dxu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsList {
            get {
                return ResourceManager.GetString("ItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJylXF1z2zgS/CspPd1VpbZI6oNU3iQ5iR3Zjm6tteru6orFWEjEs0T6KDpe3db+9x3ZAkk0yGQGftCLJDSBwWDQ6Bnwj97XdKuWhwfVe9e7Sop7Vb75QN+8+dvZ5ezvvbe9u0IlZZpnZ0l5/Esw/sXzfwm8YPjG998NQvrHQ5F/T9eqoF9nj8Verd+ccCaLC/o5zb6rrMyLw0Wpdvveu3//0dsm+/K3hzUhTsreOz/sR/7Q96LobS//8l91V16sCessPlfJ2vMJ4n+PSVam5YH+++fb9ube2Atam8cLPoTfNyE+aIxLNojvewDyghFw+zAetDXvM5uHYdg6hAH38aE5CctVvOL23fcG5tDP0+32C30O8aX6tudbcIAmWObFPue3D9ETTu35ruD7I8sVNAjfF7yooydcg/oBzKZuH8+Soszz7F/sjuDaegFiu9W4wxz9mG1SL/A7MbirI4ws964wuGOJRsN2jEE8We+myabIc7ZZYH5rqOVTWt5tuKYZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarketDLC {
            get {
                return ResourceManager.GetString("MarketDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJyt/euPW0e27Qv+Kwf7Uzdw0FCmZEt5vtmyq1xbfh1LVe59Gg0ht5Vlqy1nulNy+fhe3P/9BhcZsSLGjEn/RuQmSIAgOQfXiseM+Xr8n//2z7fvbl798evNv/2Pf/vq+v7nmw//7S/lk//2//jLb+/e/T//7b//2w/3N9cf3t7dfnb94fCbR4//X48+/n9dPrr86L9dPPofHz0rv/j1/u5fb9/c3Jdvn/92//7mzX87AX3y7d/K129v/3Vz++Hu/o+/fbj55f2//Y//z//5b++u33/4+69vCuInH/7tf1w8ffLs6smzRx9f/fd/u/vP/9/NDx/+9qZgffb6i5vrN48uCsT//7fr2w9vP/xRfvt//fc5+dOrR0+n5K+/pRDPHj2WK/hLxfiSg1zMb+OSkl98NCN/DMkvH19Mb+EJHMVnz54M9K++f/09vfanVxfjrX/x9t27/yyvP15/efPjezyClx8/kiF4dXf//o5P49XjOb2xFC4/+ljHsYIYa+HR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarketFull {
            get {
                return ResourceManager.GetString("MarketFull", resourceCulture);
            }
        }
    }
}
