//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursed_Market.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OfflineAPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OfflineAPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cursed_Market.Properties.OfflineAPI", typeof(OfflineAPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJytXVl3IjnS/S9+7gdvvVS/GTC2y6ZMG8o+Pd+Z4yNIAdlOUkwu5aL6zH+fG8qFxW7pCn8PJNuNlFKhJRQRivj7aJIYEz3pyZ3+ppPuQqVzHR39PlNJrn86KleRKnT0pJJEF/nR7//375+OpguVqWmhsy9qqY9+Pzr6afceR7+fHf90tMp0XsRzXf+EXxpQTxXq6Pe/j1aqWMgtj46fT45PcBd5P63fz+r38/r95/r9F7wDXSNxrbG41mhcazyuLcUvdRlCe7r1qbnLaX0X+VTd5QyfqrvIp+ou5/j0a/vpt7qM0+NPzaeT47q005OqDPkkZaDMujRc69JwrUvDtS4N17o0XOvScK1Lw7UuDde6NFzr0nBtSjuRMuS3M5R7ZsvFFZ+kXFzxScrFFZ+kXFzxScrFFZ+kXFzxScrFFZ+kXFyfz2y5uOKTLQPlntlycQXu5Ai9JIvTecXp//v7KDWR3vlygy6GLpEX6F3oQl2D/oUuFR3999///WkPPzVp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BloodWebData {
            get {
                return ResourceManager.GetString("BloodWebData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJytvVl3GknyPvxdfN0XsmS3230n0GZt0IDk454zRyehEqhWUcXUYoz/Z777+0Rm7cgRv2DeC/YnqKyM3CPiif/3Lgqz/N2f//p/7xZrk5pFbtNHs7Hv/nx3sQtX6/zdb+8iuzKL/Ti1WR6u7L39bqN3f5781gh8ye0mc/8R4t2XAML01cvQbLY2fTmP7I9sliTRPPmBv/tPYeI8zPfv/vx48t/ffiEzsLjUg9n+n/Fp8mrjO7v/vwoMk80mCcKk0JbsoogixXUu41UYW5sqr3IVpnaB2n2loq7xD5n9P4tGJltHpe6UEienR8ic/V9lFNX2YNG64nCh1c6DDe7C//ONe/T//aZL/P/5hkv8h/8rfmLCeJ7sFO1eWT1fkzROivz/KjUlJbveaNI8/T+UqhIYrnEnmdn9nwXG0HaebGb/l4sctsD/cwVDIa9QyMf/K/6+iM3/0nXP4zj8btPMpPvTk/ef/8/VcW2yQbKZ/5/xd6fvx8nOpvq66xbx9ERX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterData {
            get {
                return ResourceManager.GetString("CharacterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJwlkc1u2zAQhN/F5xwckW6ao38SF95GacBD0RY50DItEaYogxJj9O3NGR08WpCc/WbX/xa7m2+7afGweHNt0W2w+eSmyZX6YC/41M4WXTeot11uLsGNpdwMx6I/fAib8vtf6t9+ajo8HaFSVUVNpWGzMfqjDTxWPF4V/Wlz8mhrOnvF99VFhJDS0KXlEyjOJjzoB2YRtjPVNyoe1Ijf24Tbj+zi5GOpfnn0eUm+oQmwbRhuuBLL4czVJ4+51yfbs9t3Pp07PyOda/0Ax8Gdz7wDz6glYpWEwATb5nlVcY6HJkY9Ft13wzidLdcmbGgUN6KwgJ3rh3ZILQG1jQ0WaCb3hefv0Rf9k6F1TiPO9jmOwcfWYR1/bfIR/4pUSGO4aqmANfN+FfekMLhRnEnN6eeAjKPp1XRpRtP0ano1vZpeTa+mV9O7gle4C+G4wuGEwwnpQrqQLqQL6UK6kC6kC+lCupAupAvpQrqQLqRLoX/eATElrDw=.
        /// </summary>
        internal static string CharactersList {
            get {
                return ResourceManager.GetString("CharactersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJyNfVt327qu7n+Zz/uhTTtv5y12bm2SxjN2mzHXHnt40BZta1kWvXRp6p5x/vv+AIoiINGZ58G2AFAUSBEgAIL0//3laKt9/cv/+e9fJq4x5Wl5X7rXwmZb+8t//XJ9OJpmd8LV3Bab5dRUhL3MKluaIi8J+KvN13t82YZKHau8bJaTtqoJnLiqcq82W+QHKkp1zNvNJl/ntiT6g900E7vLy4wKF85ld65lYFbZzDSuort2JnOvK1eVBFz8Nnv3PlxchIsPuPiW17krTUXcXtkazTKNfbSmbitbU/1tXjQL92CYtZsiP94U7siE9b6wX+lyscMdTVPYp82joec9gHaaVNbsqd3lCfWV9Re7tnXtn8Q013LjP7zveKML5o0uiLf5h98DCReehAsiXVmT3ZmKGv3FPebNzlKjX2xlb11Zmof8u71xlf3O6NnOVAezpgd/y7d5QSXN3vM+AeO2Writ7eq4yX+gB6jiT2Vpq3mDt7Ztdtxnv4ZexIXvRVwQ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemsList {
            get {
                return ResourceManager.GetString("ItemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJylXF1z2zgS/CspPd1VpbZI6oNU3iQ5iR3Zjm6tteru6orFWEjEs0T6KDpe3db+9x3ZAkk0yGQGftCLJDSBwWDQ6Bnwj97XdKuWhwfVe9e7Sop7Vb75QN+8+dvZ5ezvvbe9u0IlZZpnZ0l5/Esw/sXzfwm8YPjG998NQvrHQ5F/T9eqoF9nj8Verd+ccCaLC/o5zb6rrMyLw0Wpdvveu3//0dsm+/K3hzUhTsreOz/sR/7Q96LobS//8l91V16sCessPlfJ2vMJ4n+PSVam5YH+++fb9ube2Atam8cLPoTfNyE+aIxLNojvewDyghFw+zAetDXvM5uHYdg6hAH38aE5CctVvOL23fcG5tDP0+32C30O8aX6tudbcIAmWObFPue3D9ETTu35ruD7I8sVNAjfF7yooydcg/oBzKZuH8+Soszz7F/sjuDaegFiu9W4wxz9mG1SL/A7MbirI4ws964wuGOJRsN2jEE8We+myabIc7ZZYH5rqOVTWt5tuKYZ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarketDLC {
            get {
                return ResourceManager.GetString("MarketDLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eJyt/WlvJEe2ron+lYP9qS9w0CAZQQ3nm5RSlao0bmVWqfe5uCC4lSyJVymympkqHXWj/3u7e4SZm7/LlufzGveHGBAR9oQPNixb4//9b/+4f3P36o9/3v3b//i3r2+ffrl799/+NH3y3/63P/325s3/59/++7/9+HR3++7+8eGz23fzbw4X//vFh//71cXV9X+7PPyPw/X0i38+Pf7r/vXd0/Tti9+e3t69/m9n0Cff/WX6+v7hX3cP7x6f/vjLu7tf3/7b//j//t//9ub27bu//fP1RPzk3b/9j8sPrw8ffXR18eHhv//b43/+/+9+fPeX1xPrs5sv7m5fX1xOiP/zt9uHd/fv/ph++//896T58cOPu81vvsOIi+sPt4g/FcZXHHI8dI/jCjY/fHjRa36g/375QfcUjrT91Ueb9q9+uPkBH/vF9XHT+Iv7N2/+c3r8cfPV3U9v+W34SG7DzavHp7eP/A5k7Z2u8JF0xj9ViNEXLj/Wm3mC0At6vLrq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MarketFull {
            get {
                return ResourceManager.GetString("MarketFull", resourceCulture);
            }
        }
    }
}
